### ISSUE TITLE
How do I use iotedge logging?

### ISSUE THREAD

**Issue by rploeg** [Azure-Samples/iotedge-gateway-on-kubernetes#2]
Hi,

It's more a question. I have  succes full running iotedge on kubernetes. But how can I use logging as iotedge logging to see the logs for example a streaming job?

**Comment by veyalla** [comment]
You can use the `kubectl logs` command. Specifically -
`kubectl logs <pod-name> -c <module-name> -n <edge-device-namespace>`

Personally, I use [k9s](https://github.com/derailed/k9s) to navigate around in the cluster and view logs. The [key bindings](https://github.com/derailed/k9s#key-bindings) take a bit of getting used to, but it is super efficient once you do.

Hope that helps!

**Comment by rploeg** [comment]
Thanks a lot!
